#!/usr/bin/env bun
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const examples = path.join(root, "examples");
const target = path.join(root, "src", "catalog.gen.ts");

export function generated(): string {
  const names: string[] = [];
  walk(examples, "");
  names.sort();
  const entries = names.map((name) => {
    const content = fs.readFileSync(path.join(examples, name), "utf8");
    return `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`;
  });
  return [
    "// Generated by scripts/gen-catalog.ts from examples/. Run it after an examples change.",
    "export const catalog: Record<string, string> = {",
    ...entries,
    "};",
    "",
  ].join("\n");

  function walk(dir: string, prefix: string): void {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.name.startsWith(".")) continue;
      const name = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
      if (entry.isDirectory()) walk(path.join(dir, entry.name), name);
      else names.push(name);
    }
  }
}

if (import.meta.main) {
  fs.writeFileSync(target, generated());
  process.stdout.write(`wrote ${path.relative(root, target)}\n`);
}
