#!/usr/bin/env bun
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { generateTypes } from "./generate-types.ts";

const root = fileURLToPath(new URL("..", import.meta.url));
const examples = path.join(root, "packages", "engine", "examples");
const target = path.join(root, "packages", "engine", "src", "catalog", "starter.generated.ts");

function walk(dir: string, prefix = ""): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));
  const found: string[] = [];
  for (const entry of entries) {
    const relative = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) found.push(...walk(path.join(dir, entry.name), relative));
    else found.push(relative);
  }
  return found;
}

export async function generateStarter(version: string): Promise<{ source: string; files: string[] }> {
  const carried: Record<string, string> = {};
  for (const relative of walk(examples)) carried[relative] = fs.readFileSync(path.join(examples, relative), "utf8");
  Object.assign(carried, await generateTypes());
  const files = Object.keys(carried).sort();
  const lines = files.map((relative) => `  ${JSON.stringify(relative)}: ${JSON.stringify(carried[relative])},`);
  const source = [
    "// Generated by scripts/generate-starter.ts. Run `bun run generate` after editing examples/.",
    "",
    `export const version = ${JSON.stringify(version)};`,
    "",
    "export const starterFiles: Record<string, string> = {",
    ...lines,
    "};",
    "",
  ].join("\n");
  return { source, files };
}

export async function writeStarter(version: string): Promise<string[]> {
  const { source, files } = await generateStarter(version);
  fs.writeFileSync(target, source);
  return files;
}

if (import.meta.main) {
  const manifest = (await Bun.file(path.join(root, "package.json")).json()) as { version: string };
  const files = await writeStarter(manifest.version);
  process.stdout.write(`wrote ${path.relative(root, target)}: ${files.length} files\n`);
}
